//State de productos
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
//State para el pedido

export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const CONFIRMAR_ORDENAR_PRODUCTO = "CONFIRMAR_ORDENAR_PRODUCTO ";
export const MOSTAR_RESUMEN = "MOSTAR_RESUMEN";
